# Generated by Django 5.1.2 on 2024-10-29 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_cliente_direccion_remove_cliente_telefono_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaCorriente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fecha_apertura", models.DateField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_corrientes",
                        to="accounts.cliente",
                    ),
                ),
            ],
        ),
    ]
