# Generated by Django 5.1.2 on 2024-11-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_cliente_direccion_remove_cliente_telefono_and_more"),
        ("cuentas_corrientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentacorriente",
            name="cliente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuenta_corriente_cc",
                to="accounts.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cuentacorriente",
            name="fecha_apertura",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cuentacorriente",
            name="saldo",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
