# Generated by Django 6.0.5 on 2026-06-02 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_corrientes', '0003_alter_cuentacorriente_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='fecha_apertura',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
