# Generated by Django 5.1.2 on 2024-10-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_ticket_cliente_ticket_fiado_cuentacorriente_pago"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CuentaCorriente",
        ),
    ]
