# Generated by Django 5.1.2 on 2024-11-13 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_cliente_direccion_remove_cliente_telefono_and_more"),
        ("sales", "0004_detalleventa_venta_detalleventa_venta"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="sales.venta",
            ),
        ),
        migrations.CreateModel(
            name="CuentaCorriente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuenta_corriente",
                        to="accounts.cliente",
                    ),
                ),
            ],
        ),
    ]
