# Generated by Django 5.1.2 on 2024-11-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas_corrientes", "0001_initial"),
        ("sales", "0005_ticket_venta_cuentacorriente"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cuenta_corriente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cuentas_corrientes.cuentacorriente",
            ),
        ),
    ]
