# Generated by Django 5.1.2 on 2024-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_venta_cuenta_corriente"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="tipo_de_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TARJETA", "Tarjeta"),
                    ("CUENTA_CORRIENTE", "Cuenta Corriente"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
