# Generated by Django 5.1.2 on 2024-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_venta_tipo_de_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="es_fiada",
            field=models.BooleanField(default=False),
        ),
    ]
