# Generated by Django 5.1.2 on 2024-11-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_alter_cuentacorriente_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="sales.ticket",
            ),
        ),
    ]
