# Generated by Django 5.1.2 on 2024-11-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_remove_ticket_fiado"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CuentaCorriente",
        ),
    ]
