# Generated by Django 5.2.7 on 2025-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_delete_cuentacorriente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_de_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=20, null=True),
        ),
    ]
