# Generated by Django 6.0.5 on 2026-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_venta_tipo_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
