# Generated by Django 6.0.5 on 2026-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_detalleventa_cantidad_alter_lineitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_de_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('QR', 'QR'), ('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=20, null=True),
        ),
    ]
