# Generated by Django 6.0.5 on 2026-06-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_client'),
        ('sales', '0016_alter_detalleventa_producto_alter_lineitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='accounts.cliente'),
        ),
    ]
