# Generated by Django 5.1.2 on 2024-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_categoria_product_categoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="precio",
            new_name="costo",
        ),
        migrations.AddField(
            model_name="product",
            name="porcentaje_ganancia",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=10
            ),
        ),
    ]
