# Generated by Django 5.1.2 on 2024-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_precio_product_costo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unidad_medida",
            field=models.CharField(
                choices=[("kg", "Kilogramo"), ("unidad", "Unidad")],
                default="kg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cantidad_stock",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
